# Generated by Django 2.0.13 on 2019-07-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STORENAME', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('IMAGENAME', models.CharField(max_length=50)),
                ('IMAGE', models.ImageField(default='media/default_image.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPSX', models.CharField(max_length=50)),
                ('GPSY', models.CharField(max_length=50)),
                ('LARG_CATE', models.CharField(max_length=50)),
                ('MID_CATE', models.CharField(max_length=50)),
                ('SMALL_CATE', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('IMAGENAME', models.CharField(max_length=50)),
                ('IMAGE', models.ImageField(default='media/default_image.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPSX', models.CharField(max_length=50)),
                ('GPSY', models.CharField(max_length=50)),
                ('LARG_CATE', models.CharField(max_length=50)),
                ('MID_CATE', models.CharField(max_length=50)),
                ('SMALL_CATE', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('IMAGENAME', models.CharField(max_length=50)),
                ('IMAGE', models.ImageField(default='media/default_image.jpg', upload_to='')),
            ],
        ),
    ]
