# Generated by Django 2.0.13 on 2019-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STORENAME', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('PERSONID', models.CharField(max_length=50)),
            ],
        ),
    ]
