# Generated by Django 2.0.13 on 2019-07-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
