# Generated by Django 2.0.13 on 2019-07-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190722_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualcoupon',
            old_name='PERSONID',
            new_name='USERID',
        ),
        migrations.RemoveField(
            model_name='individualcoupon',
            name='NAME',
        ),
        migrations.RemoveField(
            model_name='individualcoupon',
            name='STORENAME',
        ),
        migrations.AddField(
            model_name='individualcoupon',
            name='STOREID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='individualcoupon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
