# Generated by Django 2.0.13 on 2019-07-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190722_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualcoupon',
            old_name='STOREID',
            new_name='COUPONID',
        ),
    ]
