# Generated by Django 2.0.13 on 2019-07-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190722_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('USERID', models.CharField(max_length=50)),
                ('TITLE', models.CharField(max_length=50)),
                ('CONTENT', models.CharField(max_length=50)),
                ('IMAGE', models.ImageField(default='media/default_image.jpg', upload_to='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
