# Generated by Django 2.0.13 on 2019-07-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='picture',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
