# Generated by Django 2.0.13 on 2019-07-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EXP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='LEVEL',
            field=models.IntegerField(default=0),
        ),
    ]
