# Generated by Django 2.0.13 on 2019-07-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190722_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=20)),
                ('CONTENT', models.TextField(max_length=100)),
                ('IMAGE', models.ImageField(default='media/defualt_image.jpg', upload_to='')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='TITLE',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='picture',
            name='USERID',
            field=models.CharField(max_length=20),
        ),
    ]
