# Generated by Django 2.0.13 on 2019-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190724_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('USERID', models.CharField(max_length=50)),
                ('PICTUREID', models.IntegerField(default=0)),
                ('TITLE', models.CharField(max_length=50)),
                ('CONTENT', models.CharField(max_length=200)),
            ],
        ),
    ]
