# Generated by Django 2.0.13 on 2019-07-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='HEART',
            field=models.IntegerField(default=0),
        ),
    ]
